config/routes.rb
Rails.application.routes.draw do
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#home'
  get '/music' => 'application#music'
  get '/home' => 'application#home'
  get 'message/new' => 'comments#new'
  post 'application/new_comment' => 'application#new_comment'
  resources :comments
  resources :projects
  resources :application
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  #attr_accessor :Name,:Comment,:ContactInfo

end

app/models/project.rb
class Project < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_comment, only: [:new_comment]
  def new_comment
      unlocked_params = ActiveSupport::HashWithIndifferentAccess.new(params.permit(:Name, :Comment, :ContactInfo))
      Comment.create(Name:params[:Name],Comment:params[:Comment],ContactInfo:params[:ContactInfo])

    redirect_to root_path
  end
  def show
    redirect_to root_path
  end

  def music
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.new
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end


  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:Name, :Comment, :ContactInfo)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:name, :description, :image, :link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/application/_comment_form.html.erb
<%= form_tag("/application/new_comment", method: "post",:html => {:class => 'form'}) do %>
  <h1 class="text-primary">Reach Samir Jha <span class="glyphicon glyphicon-comment" aria-hidden="true"></span></h1>
  <div class="form-group">
    <%= label_tag(:Name, "Name: ") %>
    <%= text_area_tag :Name , "",class:'form-control',placeholder: 'Anonymous!!' %>
    <br/>
    <%= label_tag(:Comment, "Message: ") %>
    <%= text_area_tag(:Comment,"", class: 'form-control',placeholder: 'Something Nice...') %>
    <br/>
    <%= label_tag(:ContactInfo, "Contact Information: ") %>
    <%= text_area_tag(:ContactInfo,"", class: 'form-control',placeholder: 'Will I spam you? YES!!') %>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <%= submit_tag("Post Message", class: 'form-control btn btn-danger', style: 'zoom: 150%;') %>
  </div>
<% end %>

app/views/application/new_comment.html.erb
<%= render 'application/comment_form' %>

app/views/comments/_form.html.erb
<%= form_for(comment,:html => {:class => 'form'}) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="row">
      <div class = "col-sm-12">
  <div class="form-group">
    <%= f.label :Name %>
    <%= f.text_field(:Name, class:"form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :Comment %>
    <%= f.text_field(:Comment, class:"form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :"Contact Info" %>
    <%= f.text_field(:ContactInfo, class:"form-control") %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
        </div>
      </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th>Contactinfo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.Name %></td>
        <td><%= comment.Comment %></td>
        <td><%= comment.ContactInfo %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', root_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.Name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.Comment %>
</p>

<p>
  <strong>Contactinfo:</strong>
  <%= @comment.ContactInfo %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<meta name=viewport content="width=device-width, initial-scale=1.0">
<meta name="description" content="Samir Jha | Biography and Employment History">
<style>.navbar-nav li{display:inline-block;width:20%;margin:0;padding:0}</style>
<head>
  <title><%= yield(:title) %>Samir Jha</title>
  <script type=application/ld+json>
    {
      "@context": "http://schema.org",
      "@type": "Person",
      "address": {
        "@type": "PostalAddress",
        "addressLocality": "Raleigh",
        "addressRegion": "NC",
        "postalCode": "27606",
        "streetAddress": "2704 H"
      },
      "email": "mailto:samirjha1525@gmail.com",
      "image": "https://pbs.twimg.com/profile_images/848736334009311236/bVLwhPl0_400x400.jpg",
      "jobTitle": "Software Developer",
      "name": "Samir Jha",
      "alumniOf": "NC State University",
      "birthPlace": "Bokaro, IN",
      "birthDate": "1990.08.15",
      "height": "5'11",
      "gender": "Male",
      "nationality": "Indian",
      "url": "www.samirjha.com",
	    "sameAs" : [ "https://www.facebook.com/You.just.stalked.Samir",
      "https://linkedin.com/in/deeplearningsamirjha/"
      ]
    }
    </script>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href=/favicon.ico />
  <link href=//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css rel=stylesheet />
  <script src=https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js></script>
  <link href=https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css rel=stylesheet />
  <script src=https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js></script>
  <script src=https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js></script>
  <link rel=stylesheet type=text/css href="https://fonts.googleapis.com/css?family=Tangerine" />
  <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
  <%= javascript_include_tag :defaults%>
  <script>(function(m,l,g,i,k,n,a){m.GoogleAnalyticsObject=k;m[k]=m[k]||function(){(m[k].q=m[k].q||[]).push(arguments)},m[k].l=1*new Date();n=l.createElement(g),a=l.getElementsByTagName(g)[0];n.async=1;n.src=i;a.parentNode.insertBefore(n,a)})(window,document,"script","https://www.google-analytics.com/analytics.js","ga");ga("create","UA-90039872-1","auto");ga("send","pageview");</script>
  <nav class="navbar navbar-fixed-top" style=border-color:transparent;width:100%>
    <div class=container-fluid>
      <div class="collapse navbar-collapse" style=width:100%>
        <ul class="nav navbar-nav" style="width:100%; zoom: 130%">
          <li>
            <button id=Home class="btn btn-info navbar-btn">
              <span class="glyphicon glyphicon-home" aria-hidden=true></span> <span> Home</span>
            </button>
          </li>
          <li>
            <button id=AboutMe class="btn btn-info navbar-btn">
              <span class="glyphicon glyphicon-user" aria-hidden=true></span> <span id=AboutButtonText> About Samir Jha</span>
            </button>
          </li>
          <li>
            <button id=ResumeButton class="btn btn-info navbar-btn" onclick="window.open('https://drive.google.com/file/d/1nQQp7oUBPTK2s22kHhBAzaKlil39MZ0n/view?usp=sharing')">
              <span class="glyphicon glyphicon-file" aria-hidden=true></span> <span> Samir Jha - Resume</span>
            </button>
          </li>
          <li>
            <button id=proj type=button style="animation:spin 1s infinite" class="btn btn-success navbar-btn">
              <span id=folder class="glyphicon glyphicon-folder-close" aria-hidden=true></span> <span id=ProjText> See Projects</span>
            </button>
          </li>
          <li>
            <button id=SocialApp style="animation:spin 1s infinite" class="btn btn-primary navbar-btn" onclick="window.open('https://socialnewsverifier.herokuapp.com/')">
              <span class="glyphicon glyphicon-new-window" aria-hidden=true></span> <span>News Verifier</span>
            </button>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</head>
<body style="background-image:url('/farm.jpg');background-size:cover">
<%= yield %>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project,:html => {:class => 'form'}) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class = "col-sm-12">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field(:name, class:"form-control") %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field(:description, class:"form-control") %>
      </div>

      <div class="form-group">
        <%= f.label :"Image link" %>
        <%= f.text_field(:image, class:"form-control") %>
      </div>

      <div class="form-group">
        <%= f.label :"Github link" %>
        <%= f.text_field(:link, class:"form-control") %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', root_path %>

app/views/projects/index.html.erb
<div style="padding: 10%">
<p id="notice"><%= notice %></p>

<table id="example" class="table table-striped table-bordered hover" cellspacing="2" width="100%">
  <thead>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Image</th>
    <th>Details </th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.description %></td>
      <td><img src ="<%= project.image %>"></td>
      <td><a href ="<%= project.link %>">View Details/Code</a></td>
      <td><%= link_to 'Show', project %> | <%= link_to 'Edit', edit_project_path(project) %> | <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br/>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', root_path %>

app/views/projects/show.html.erb
<style>
  p{
    font-family: Fredericka the Great, sans-serif;
    font-size: 110%;
    color: white;
  }
</style>
<p id="notice"><%= notice %></p>
<div style="padding: 10%">
<p>
  <img src = "<%= @project.image %>">
</p>
  <p align="justify">
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p align="justify">
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p align="justify">
  <strong>Github Url:</strong>
  <a href = "<%= @project.link %>"> View on Github </a>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
</div>